### ISSUE TITLE
"toString" for Variant

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/genophenocorr#109]
It would be nice to be able to do
```
 print(f"[WARNING] Could not find annotation of variant {v} for {reference_tx_id}")
```
instead of (as now)
```
print(f"[WARNING] Could not find annotation of variant {v.variant_coordinates.variant_key} for {reference_tx_id}")
```
to get
```
[WARNING] Could not find annotation of variant 12_112473023_112473023_A_G for NM_002834.5
```

**Comment by ielis** [comment]
I think the exact details of what `Variant` still need to be worked out. Let's keep this issue around.

**Comment by ielis** [comment]
Yes, this is a good thing to do.

When thinking about generating a `str` for `Variant`, there are 3 use cases to keep in mind:

1. `toString()`, as in Java, represents the internal state of the object. In Python, `__repr__` is the equivalent function. The method should *always* be implemented on the lowest class of the class hierarchy and represent the internal state of the class. It is most useful for value objects
2. `variant key` - we need a way to identify a variant uniquely, to use e.g. in `VariantKeyPredicate`. We also use it to name the cache files (and there is an issue with it #183 ). This can be thought of as a variant hash
3. variant formatting - use in pretty tables designed for humans. This should be implemented in a formatter, a class that takes a variant and returns a `str` following Peter's 6-step algorithm from above

**At this place, we are only dealing with the 3rd concern.**

The issue is done when we have the following:
- we have a formatter class that takes a variant and returns a `str`. The formatter should probably take no non-default `__init__` arguments
- we have tests that show it works
- (optional) use the formatter to create the pretty tables
