### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/genophenocorr#135]
- I would suggest upgrading to mkdocs -- it will be easier to make it look really nice
- I will start writing some background about things that do not depend on our API, such as how to decide which transcript to use and where to find relevant information.
@ielis @lnrekerle  -- OK?

**Comment by ielis** [comment]
@pnrobinson I know nothing about mkdocs and I would prefer staying with Sphinx because I already know Sphinx and I am not aware about any limitation. Perhaps we can discuss this the next time we speak? I am curious about the advantages MKDocs can provide.

**Comment by ielis** [comment]
OK, as long you can show how to do the following:
- how mkdocs runs doctests to ensure the documentation stays up to date
- how to *automatically* generate the API documentation (no manual labeling of classes that correspond to the public API)
- how to link out to documentation of Python standard library + numpy + others
- (nice to have) - how to handle documentation for multiple versions of a package

Otherwise I would really REALLY prefer not spending any mental bandwith on this topic
