### ISSUE TITLE
Create a predicate that tests if a variant affects a Region given by the User.

### ISSUE THREAD

**Issue by lnrekerle** [monarch-initiative/genophenocorr#174]
Rather than only allowing users to pick a specific domain, create a predicate that will allow a user to give a region of amino acids on the protein and look for whether a variant affects an amino acid in that region. 

Make sure there is a matching predicate for comparing two regions and for comparing a recessive variant.

**Comment by pnrobinson** [comment]
@lnrekerle 
Thanks!
One nice way of doing issues like this is to also write something like this
"This issue is closeable if a unit test is passed in which the predicate returns true for a region within the indicated range and false for other regions. Document to do about edge conditions -- here, we will consider if the user has a range of 40-80 that a mutation that affects amino acid 40 or 80 is "inside" and that "outside" begins at residues 39 and 81. Have tests for the edge conditions.

**Comment by pnrobinson** [comment]
This means that a reviewer can run the tests and check that your code does what it is supposed to do, which should make the whole process go more quickly.

**Comment by ielis** [comment]
@lnrekerle 

> Make sure there is a matching predicate for comparing two regions and for comparing a recessive variant.

Implementing a predicate for each mode of inheritance is not a good idea because it is basically a code duplication. Code duplication is never a good idea. 
The way the predicates are implemented will change after finishing #159 . 

For now, please just implement the dominant version, it will be enough.
