### ISSUE TITLE
set pval_correction

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/genophenocorr#187]
The constructor sets the default to Bonferroni.
If the user enters
config.pval_correction()
or
pval_correction(None)
I do not think this will set to no MTC, and also I think thisAPI is not intuitive.
It would be better to be able to use a string "none" (lower case, not the Python None)
```
    @pval_correction.setter
    def pval_correction(self, pval_correction: typing.Optional[str]):
        """
        :param pval_correction: a `str` with the name of the desired multiple testing correction method or `None`
          if no MTC should be applied.
        """
        if pval_correction in P_VAL_OPTIONS:
            self._pval_correction = pval_correction
        else:
            self._logger.warning('Ignoring invalid `pval_correction` value %s. Using %s correction.', pval_correction,
                                 self._pval_correction)
```

**Comment by ielis** [comment]
I think this should be largely OK and I do not see the errors or issues here.

There are no issues here:
> If the user enters
> ```
> config.pval_correction()
> ```

If the above is executed, the code will correctly explode

```python
from genophenocorr.analysis import CohortAnalysisConfiguration

config = CohortAnalysisConfiguration()
config.pval_correction()
```
produces
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 config.pval_correction()

TypeError: 'str' object is not callable
```

`pval_correction` is a property, hence this is what should happen
```
>>> config.pval_correction
'bonferroni'
```

Next, regarding unsetting MTC. It *is* possible to avoid MTC by 
```python
config.pval_correction = None
```
I think using `None` instead of `'none'` is more idiomatic and easier to keep track of by leveraging the type system.

> I do not think this will set to no MTC,

Yes it does unset the MTC, the MTC will [not be done](https://github.com/monarch-initiative/genophenocorr/blob/2c7f645791f070b95a18db923590f389bef75e11/src/genophenocorr/analysis/_gp_analysis.py#L499)

The API intuitiveness is another question and we may want to update. We must, however keep the following in mind:

* we need to have a default config to cover the most common use case
* it must be impossible to mis-configure the analysis. The errors must be reported as early as possible

A builder would be the best way to do this, but builders in Python are not too great due to issues with line wrapping. That's why we use properties.

I updated the logic in #189 a bit and I think it should be largely OK.

However, @pnrobinson please point out if you think we should explode instead of logging, or if there are any other things you don't like.

**Comment by ielis** [comment]
I think this has been done.
